[package]
name = "cairo_erc_2981"
version = "2.0.0"

[lib]

[dependencies]
starknet = "2.6.4"
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.14.0" }

[[target.starknet-contract]]
sierra = true
casm = true