[package]
name = "cairo_erc_2981"
version = "2.0.0"

[lib]

[dependencies]
starknet = ">=2.2.0"
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.7.0-rc.0" }

[[target.starknet-contract]]
sierre = true
casm = true